# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=30, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('api_provider', models.CharField(max_length=50, verbose_name='\u670d\u52a1\u5546')),
                ('api_description', models.TextField(verbose_name='\u670d\u52a1\u63cf\u8ff0')),
                ('api_url', models.CharField(blank=True, max_length=200, verbose_name='\u63a5\u53e3\u5730\u5740')),
                ('api_method', models.CharField(blank=True, max_length=45, verbose_name='\u8bf7\u6c42\u65b9\u6cd5')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u7ba1\u7406',
                'verbose_name_plural': '\u670d\u52a1\u7ba1\u7406',
            },
        ),
    ]
