# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0002_auto_20161210_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIWorks',
            new_name='ApiInfo',
        ),
        migrations.AlterModelTable(
            name='apiinfo',
            table='api_info',
        ),
    ]
