# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0003_auto_20161211_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='api_method',
            field=models.IntegerField(blank=True, verbose_name='\u8bf7\u6c42\u65b9\u6cd5'),
        ),
    ]
