# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0006_auto_20161211_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apierrno',
            old_name='param_intro',
            new_name='errno_intro',
        ),
    ]
