# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiworks', '0007_auto_20161212_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('api_status', models.IntegerField(default=1, verbose_name='API\u72b6\u6001')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('api_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiworks.ApiInfo', verbose_name='\u6240\u5c5e\u670d\u52a1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'api_permission',
                'verbose_name': 'API\u6743\u9650\u7ba1\u7406',
                'verbose_name_plural': 'API\u6743\u9650\u7ba1\u7406',
            },
        ),
        migrations.AlterModelOptions(
            name='apierrno',
            options={'verbose_name': '\u9519\u8bef\u7801\u7ba1\u7406', 'verbose_name_plural': '\u9519\u8bef\u7801\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='apiparam',
            options={'verbose_name': '\u53c2\u6570\u7ba1\u7406', 'verbose_name_plural': '\u53c2\u6570\u7ba1\u7406'},
        ),
    ]
