# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0009_auto_20161212_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001\u7801')),
                ('result', models.CharField(blank=True, max_length=200, verbose_name='\u8fd4\u56de\u7ed3\u679c')),
                ('consumed_time', models.IntegerField(default=0, verbose_name='\u6d88\u8017\u65f6\u95f4')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'api_log',
                'verbose_name': '\u65e5\u5fd7\u7ba1\u7406',
                'verbose_name_plural': '\u65e5\u5fd7\u7ba1\u7406',
            },
        ),
        migrations.RenameField(
            model_name='apierrno',
            old_name='createtime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='apiparam',
            old_name='createtime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='apipermission',
            old_name='createtime',
            new_name='created_time',
        ),
    ]
