# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0010_auto_20161213_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiworks.ApiInfo', verbose_name='\u6240\u5c5e\u670d\u52a1'),
            preserve_default=False,
        ),
    ]
