# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0011_apilog_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='request',
            field=models.TextField(blank=True, verbose_name='\u8bf7\u6c42\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='apierrno',
            name='errno_intro',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='result',
            field=models.TextField(blank=True, verbose_name='\u8fd4\u56de\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='apiparam',
            name='param_description',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
    ]
