# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0012_auto_20161213_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u56fe\u7247\u94fe\u63a5'),
        ),
    ]
