# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0015_auto_20161221_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='api_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u5173\u952e\u5b57'),
        ),
    ]
