# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0017_apilog_error_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='request_id',
            field=models.IntegerField(null=True, verbose_name='\u8bf7\u6c42ID'),
        ),
    ]
