# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0018_apilog_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='request_id',
            field=models.CharField(max_length=50, null=True, verbose_name='\u8bf7\u6c42ID'),
        ),
    ]
