# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiworks', '0019_auto_20170109_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='api_status',
            field=models.IntegerField(default=0, verbose_name='API\u72b6\u6001'),
        ),
    ]
