# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20160507_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlinks',
            name='site',
        ),
        migrations.DeleteModel(
            name='FriendLinks',
        ),
    ]
