# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0009_auto_20161020_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuinfo',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
