# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_auto_20161213_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8054\u7cfb\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
    ]
