# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0004_auto_20161214_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u83dc\u5355\u540d\u79f0')),
                ('pid', models.IntegerField(null=True, verbose_name='\u4e0a\u7ea7\u83dc\u5355')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='\u94fe\u63a5')),
                ('order', models.IntegerField(null=True, verbose_name='\u6392\u5e8f')),
                ('visible', models.IntegerField(default=1, null=True, verbose_name='\u662f\u5426\u53ef\u89c1')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4e2d\u5fc3\u7ba1\u7406',
                'verbose_name_plural': '\u7528\u6237\u4e2d\u5fc3\u83dc\u5355\u7ba1\u7406',
            },
        ),
    ]
